apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    mysql: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      mysql: mysql
  template:
    metadata:
      labels:
        mysql: mysql
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: test
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    mysql: mysql
spec:
  ports:
    - port: 3306
  selector:
    mysql: mysql
