apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-probes
target:
  group: apps
  version: v1
  kind: Deployment
  name: app
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: app
  spec:
    template:
      spec:
        containers:
          - name: app
            livenessProbe:
              httpGet:
                path: /actuator/info
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 3
              timeoutSeconds: 5
            readinessProbe:
              initialDelaySeconds: 60
              periodSeconds: 10
              httpGet:
                path: /actuator/health
                port: 8080
