apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../mysql
namePrefix: petclinic-
# You can either include ../../mysql or use commonLabels here, but not both, 
# otherwise the app service selects the mysql pods
# commonLabels:
#   app: petclinic
transformers:
- ../../mysql/transformer
- ../../actuator
images:
  - name: dsyer/template
    newName: springio/petclinic
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - SPRING_CONFIG_LOCATION=classpath:/,file:///config/bindings/mysql/meta/
      - MANAGEMENT_ENDPOINTS_WEB_BASEPATH=/actuator
      - DATABASE=mysql
